todoapp/blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', NewsList.as_view(), name="home"),
    path('news/<int:pk>', NewsDetail.as_view(), name="newsdetail"),

]

todoapp/todo/urls.py
from django.urls import path
from .views import *
from account import views as acv

app_name = 'todo'
urlpatterns = [
    path('', acv.TaskView.as_view(), name='tasklist'),
    path('<str:id>/complete/', acv.TaskComplete.as_view()),
    path('<str:id>/delete/', acv.TaskDelete.as_view()),
    path('login/', acv.Login.as_view(), name="login"),
    path('logout/', acv.Logout.as_view(), name="logout"),
    path('register/', acv.register.as_view(), name="register"),
]

todoapp/todoapp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('task/', include('todo.urls', namespace="todo")),
                  path('', include('blog.urls', namespace='blog')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todoapp/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    pass

todoapp/blog/models.py
from django.db import models


# Create your models here.
class news(models.Model):
    title = models.CharField(max_length=150)
    text = models.TextField()

todoapp/todo/models.py
from django.db import models
from account.models import User


# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=140)
    date = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name='tasks')

    class Meta:
        ordering = ['completed', 'date']

todoapp/account/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None
        self.fields['username'].help_text = None

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

todoapp/todo/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title']

todoapp/account/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, View
from django.contrib.auth.views import LoginView, LogoutView
from todo.models import Task
from todo.forms import TaskForm
from django.http import JsonResponse
from django.forms.models import model_to_dict
from django.shortcuts import render, reverse
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RegisterForm


# Create your views here.


class Login(LoginView):
    pass


class register(CreateView):
    form_class = RegisterForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('todo:login')


class Logout(LoginRequiredMixin, LogoutView):
    pass


class TaskView(LoginRequiredMixin, View):
    def get(self, request):
        tasks = list(Task.objects.filter(owner=self.request.user).values())
        if request.is_ajax():
            return JsonResponse({'tasks': tasks}, status=200)

        return render(request, 'task/task.html')

    def post(self, request):
        bound_form = TaskForm(request.POST)

        if bound_form.is_valid():
            bound_form.instance.owner = request.user
            new_task = bound_form.save()
            return JsonResponse({'task': model_to_dict(new_task)}, status=200)

        return redirect('tasklist')


class TaskComplete(LoginRequiredMixin, View):
    def post(self, request, id):
        task = Task.objects.get(id=id)
        task.completed = True
        task.save()
        return JsonResponse({'task': model_to_dict(task)}, status=200)


class TaskDelete(LoginRequiredMixin, View):
    def post(self, request, id):
        task = Task.objects.get(id=id)
        task.delete()
        return JsonResponse({'result': 'ok'}, status=200)

todoapp/blog/views.py
from django.http import Http404
from django.shortcuts import render
from .models import *
from django.views.generic import ListView, DetailView


# Create your views here.

class NewsList(ListView):
    model = news
    context_object_name = 'newsList'


class NewsDetail(DetailView):
    model = news
    template_name = "blog/newsInner.html"
    context_object_name = 'instance'

todoapp/todo/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.generic import View, ListView, CreateView
from django.contrib.auth.views import LoginView, LogoutView
from django.http import JsonResponse
from django.forms.models import model_to_dict

todoapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html dir="rtl">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <link href='https://cdn.fontcdn.ir/Font/Persian/Sahel/Sahel.css' rel='stylesheet' type='text/css'>
    {#    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/3.0.0-beta.15/vue.cjs.js"></script>#}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.js"></script>
    <title>ToDO App</title>
    {% block style %}
    {% endblock %}
</head>
<body>

<div class="container">
    {% if user.is_authenticated %}
        <span class="float-left mt-5">You logged in as {{ user }}</span>
        <a href="{% url 'todo:logout' %}" class="float-left mt-5"> logout &nbsp;&nbsp;</a>
    {% endif %}
    <div class="row">
        <div class="col-8 mx-auto mt-5">
            {% block content %}


            {% endblock %}
        </div>
    </div>

</div>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/vue"></script>
<script src="{% static 'main.js' %}" type="text/javascript"></script>

</body>
</html>

todoapp/templates/blog/newsInner.html
{% load static %}
<!DOCTYPE html>

<html lang="en" class="home-html">

<head>

    <!--Important Meta Tags-->
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <!--baraye inke website rooye hame moroorgar ha kar kone va mige hamontori website ro baz konan ke Edge mikone-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--Baraye inke website responsive bashe makhsosan baraye mobile-->

    <!--Title-->
    <title>وبسایت خبری</title>

    <!--FavIcon-->
    <!--    <link rel="icon" type="image/png" href="./res/favicon.png">-->

    <!--Fontawesome-->
    <link rel="stylesheet" href="{% static 'regester/css/font-awesome/css/font-awesome.min.css' %} ">

    <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'regester/css/style.css' %}">

</head>


<body>

<div class="container-news">

    <div>

        <a href="{% url 'blog:home' %}">
            <div class="home-button">
                <span><i class="fa fa-home"></i></span>
            </div>
        </a>

    </div>

    <div class="news">
        <h2>{{ instance.title }}</h2>
        <hr>
        <p>
            {{ instance.text }}
        </p>
    </div>

</div>


</body>

</html>

todoapp/templates/blog/news_list.html
{% load static %}
<!DOCTYPE html>

<html lang="en" class="home-html">

<head>

    <!--Important Meta Tags-->
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <!--baraye inke website rooye hame moroorgar ha kar kone va mige hamontori website ro baz konan ke Edge mikone-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--Baraye inke website responsive bashe makhsosan baraye mobile-->

    <!--Title-->
    <title>Todo List project</title>

    <!--FavIcon-->
    <!--    <link rel="icon" type="image/png" href="./res/favicon.png">-->

    <!--Fontawesome-->
    <link rel="stylesheet" href="{% static 'regester/css/font-awesome/css/font-awesome.min.css' %}">

    <!--Custom CSS-->
    <link rel="stylesheet" href=" {% static 'regester/css/style.css' %}">

</head>


<body>

<div class="container">


    <div class="buttons">
        <a href="{% url 'todo:login' %}" style="margin-bottom: 32px;">
            <button class="login english-font">login</button>
        </a>
        <a href="{% url 'todo:register' %} " style="margin-bottom: 32px; display: block;">

            <button class="register english-font">register</button>
        </a>
    </div>

    <div class="links">
        {% for news in newsList %}
            <a href="news/{{ news.pk }}">
                <div class="link">
                    <span>{{ news.title }} </span>
                </div>
            </a>
        {% endfor %}


    </div>


</div>


</body>

</html>

todoapp/templates/task/task.html
{% extends 'base.html' %}
{% block style %}

    <style type="text/css">
        body {
            font-family: Sahel;
            text-align: right;
        }

        .line-through {
            text-decoration: line-through;
        }
    </style>
{% endblock %}
{% block content %}
    {% verbatim %}
    <div id="app">

        <form @submit.prevent="createTask">

            <div class="container">
                <div class="row form-group">
                    <div class="col-12 py-3">
                        <h1>پروژه لیست کارها</h1>
                    </div>
                    <div class="col-8">
                        <label>Create New Task</label>
                        <input class="form-control mb-3" v-model="task">
                    </div>
                    <div class="d-flex flex-column">
                        <button class="btn btn-success mt-auto mb-3">Create</button>
                    </div>
        </form>
        <div class="col-10 mt-2">
            <div class="card mt-2" v-for="(task , index) in taskList" @click="completeTask(task.id, index)"
                 :class="{'completed': task.completed}">
                <div class="card-body">
                    {{ task.title }}
                    <button type="button" class="close float-left" @click.stop="deleteTask(task.id, index)">
                        <span class="fa fa-trash"></span>
                    </button>
                </div>

            </div>

        </div>

        {% endverbatim %}
{% endblock %}